### PR TITLE
[add] react-native-gifted-messenger

### PR DESCRIPTION
**Pull request by dsibiski**

### CODE REVIEW

**Comment by dsibiski** [comment]
@dabbott In order to make this work best out of the box, as an example, I decided to hardcode the width & height values using Dimensions. However of course, this won't work without the user adding Dimensions. Is there a way that I can auto add this via the `imports` section of the entry in the package.json?

**Comment by dabbott** [comment]
Yup - just add

```
"imports": {
  "react-native-gifted-messenger": "GiftedMessenger",
  "react-native": [
    "View",
    "Dimensions"
  ]
}
```

and uh... make it `schemaVersion: 0.0.2` ;)

(side note: although it might seem logical, even though react-native is in imports, don't correspondingly add it in dependencies - we just assume it exists)

**Comment by dsibiski** [comment]
Ah perfect! I'll get this updated then...also, why scheme 0.0.2?

**Comment by dabbott** [comment]
completely undocumented, but I didn't add multiple imports in 0.0.1. so I incremented the version for that. the private beta vers of Deco will only show components of schema 0.0.1.

**Comment by dsibiski** [comment]
aaaah, makes sense...I thought it was specific for the component. Thanks for explaining.

**Pull request merged**
